language: node_js
node_js:
  - 8
  - 10
  - 12
os:
  - linux
  - osx
env:
  matrix:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
matrix:
  fast_finish: true
deploy:
- provider: npm
  skip_cleanup: true
  email: pact-foundation@googlegroups.com
  api_key:
    secure: "go8wn2ldd/YAbvqAnzG5/wkyoCkZxbJRo93lLkKCpFqtTsrxytk3h5Myx2Y/FrrQbV502DzVghhC8nyhhBTvxZTdHsqALJLAe7ACuVXtlsS+ERS75Pu29vKLAIG46j8IcT6eZBmM7RXtAnYYdCTw2vXPs+ea1CQbQ1GhbSRlTzRmrpAQsOOCTrp4WTN5YNQyTKJR9d156HILJD/29LMxlFNM6Kl7V+iE8oFwRNtoacB/rwgQEzgdDi4mNvoxPuBSBthaatXoL4Ba9niiJbRCrrgFGZ8mL6/O+ostVGOvKsvDIsj6kCzvJrkIiO8tlRa88stt/auQeS5zRNBdAVpSH2MAhGh4QrPfSyg1JOSVnIKqs+xqEXvn17ugywYBixnliy0Kugqe9yikGX8DopAGNBViBVel01SR6nA58gbWkNGLcyHuBsTaKBYUrWTh7zCaqYQdcRJBnPkLbCf9IU2ZdZuCKa8pm+B+J31zWeS9d6qTVu57AUzF5S4yUVn7MJJKP3/AlaSMZa4OOW4R4Al2/UewxcwU+kd0uboW33SOROXj62pL/1M0g0MUKg4zh9aRrz11okM+bQunKfiPTHVSRspiBUGrtNJJ4fIGe5bZ67rCsbl3rP69lv7f89XTmAsLYqMOGseUmfFtAtI5Fg1rtzTruPC+DYnTSkxa/jwdkCA="
  on:
    branch: master
    tags: true
    node: 12
after_failure:
- find . -iname '*.log' -print0 | xargs -0 cat
